# Generated by Django 4.0.2 on 2022-02-25 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentvehicle',
            name='user',
        ),
    ]
